version: "3"
services:
  node_backend:
    build: ./backend
    expose:
      - "3001"
    ports: 
      - "3001:3001"
    volumes:
      - ./backend:/app
      
  react_frontend:
    build: ./client
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app