version: '3'

services:
  react_base:
    image: react_base
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
  node_base:
    image: node_base
    ports: 
      - "3001:3001"
    volumes:
      - ./backend:/app